spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/byebuying
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ByeBuying.Manager@gmail.com
    password: encore123!@
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
  security:
    oauth2:
      client:
        registration:

          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

          facebook:
            client-id:
            client-secret:
            scope:
              - email
              - public_profile

          naver:
            client-id:
            client-secret:
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            client-authentication-method: post
            redirect-uri: http://localhost:8081/login/oauth2/code/naver

          kakao:
            client-id:
            client-secret:
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao

        provider: # 네이버, 카카오는 provider 지원이 안되기 때문에 등록해줘야함
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response # 회원 정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC # JWT를 암호화 하기 위한 암호화 키 (32글자면 된다)
    accesstokenExpiration: 600000 # token 만료 기간 (10 min * 60s * 1000ms)
    refreshtokenExpiration: 864000000  # token 만료 기간 (24h * 60min * 60s * 1000ms)
  oauth2:
    # OAuth2 공급자로 성공적으로 인증 한 후 사용자에 대한 인증 토큰을 생성하고 토큰을
    # 프론트 엔드 클라이언트가 /oauth2/authorize 요청에서 지정한 redirectUri 입니다.
    # 쿠키는 모바일 클라이언트에서 잘 작동하지 않기 때문에 사용하지 않습니다
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
server:
  port: 8081