server:
  address: 127.0.0.1
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/byebuying
    username: root
    password: qwer1234
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ByeBuying.Manager@gmail.com
    password: encore123!@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true